using UnityEngine;
using System.Collections.Generic;

public class LevelScoresDatabase : MonoBehaviour {

    public List<LevelScores> levelScores;

    public static LevelScoresDatabase levelScoresDatabase;

    void Start()
    {
        levelScoresDatabase = GetComponent<LevelScoresDatabase>();

        levelScores.Add(new LevelScores("Level 0", false, 0, 0));
        levelScores.Add(new LevelScores("Level 01", false, 0, 0));
        levelScores.Add(new LevelScores("Level 02", false, 0, 0));
        levelScores.Add(new LevelScores("Level 03", false, 0, 0));
        levelScores.Add(new LevelScores("Level 04", false, 0, 0));
        levelScores.Add(new LevelScores("Level 05", false, 0, 0));
        levelScores.Add(new LevelScores("Level 06", false, 0, 0));
        levelScores.Add(new LevelScores("Level 07", false, 0, 0));
        levelScores.Add(new LevelScores("Level 08", false, 0, 0));
        levelScores.Add(new LevelScores("Level 09", false, 0, 0));
        levelScores.Add(new LevelScores("Level 10", false, 0, 0));
        levelScores.Add(new LevelScores("Level 11", false, 0, 0));
        levelScores.Add(new LevelScores("Level 12", false, 0, 0));
        levelScores.Add(new LevelScores("Level 13", false, 0, 0));
        levelScores.Add(new LevelScores("Level 14", false, 0, 0));
        levelScores.Add(new LevelScores("Level 15", false, 0, 0));
        levelScores.Add(new LevelScores("Level 16", false, 0, 0));
        levelScores.Add(new LevelScores("Level 17", false, 0, 0));
        levelScores.Add(new LevelScores("Level 18", false, 0, 0));
        levelScores.Add(new LevelScores("Level 19", false, 0, 0));
        levelScores.Add(new LevelScores("Level 20", false, 0, 0));
        levelScores.Add(new LevelScores("Level 21", false, 0, 0));
        levelScores.Add(new LevelScores("Level 22", false, 0, 0));
        levelScores.Add(new LevelScores("Level 23", false, 0, 0));
        levelScores.Add(new LevelScores("Level 24", false, 0, 0));
        levelScores.Add(new LevelScores("Level 25", false, 0, 0));
        levelScores.Add(new LevelScores("Level 26", false, 0, 0));
        levelScores.Add(new LevelScores("Level 27", false, 0, 0));
        levelScores.Add(new LevelScores("Level 28", false, 0, 0));
        levelScores.Add(new LevelScores("Level 29", false, 0, 0));
        levelScores.Add(new LevelScores("Level 30", false, 0, 0));
        levelScores.Add(new LevelScores("Level 31", false, 0, 0));
        levelScores.Add(new LevelScores("Level 32", false, 0, 0));
        levelScores.Add(new LevelScores("Level 33", false, 0, 0));
        levelScores.Add(new LevelScores("Level 34", false, 0, 0));
        levelScores.Add(new LevelScores("Level 35", false, 0, 0));
        levelScores.Add(new LevelScores("Level 36", false, 0, 0));
        levelScores.Add(new LevelScores("Level 37", false, 0, 0));
        levelScores.Add(new LevelScores("Level 38", false, 0, 0));
        levelScores.Add(new LevelScores("Level 39", false, 0, 0));
        levelScores.Add(new LevelScores("Level 40", false, 0, 0));
        levelScores.Add(new LevelScores("Level 41", false, 0, 0));
        levelScores.Add(new LevelScores("Level 42", false, 0, 0));
        levelScores.Add(new LevelScores("Level 43", false, 0, 0));
        levelScores.Add(new LevelScores("Level 44", false, 0, 0));
        levelScores.Add(new LevelScores("Level 45", false, 0, 0));
        levelScores.Add(new LevelScores("Level 46", false, 0, 0));
        levelScores.Add(new LevelScores("Level 47", false, 0, 0));
        levelScores.Add(new LevelScores("Level 48", false, 0, 0));
        levelScores.Add(new LevelScores("Level 49", false, 0, 0));
        levelScores.Add(new LevelScores("Level 50", false, 0, 0));
        levelScores.Add(new LevelScores("Level 51", false, 0, 0));
        levelScores.Add(new LevelScores("Level 52", false, 0, 0));
        levelScores.Add(new LevelScores("Level 53", false, 0, 0));
        levelScores.Add(new LevelScores("Level 54", false, 0, 0));
        levelScores.Add(new LevelScores("Level 55", false, 0, 0));
        levelScores.Add(new LevelScores("Level 56", false, 0, 0));
        levelScores.Add(new LevelScores("Level 57", false, 0, 0));
        levelScores.Add(new LevelScores("Level 58", false, 0, 0));
        levelScores.Add(new LevelScores("Level 59", false, 0, 0));
        levelScores.Add(new LevelScores("Level 60", false, 0, 0));
        levelScores.Add(new LevelScores("Level 61", false, 0, 0));
        levelScores.Add(new LevelScores("Level 62", false, 0, 0));
        levelScores.Add(new LevelScores("Level 63", false, 0, 0));
        levelScores.Add(new LevelScores("Level 64", false, 0, 0));
        levelScores.Add(new LevelScores("Level 65", false, 0, 0));
        levelScores.Add(new LevelScores("Level 66", false, 0, 0));
        levelScores.Add(new LevelScores("Level 67", false, 0, 0));
        levelScores.Add(new LevelScores("Level 68", false, 0, 0));
        levelScores.Add(new LevelScores("Level 69", false, 0, 0));
        levelScores.Add(new LevelScores("Level 70", false, 0, 0));
        levelScores.Add(new LevelScores("Level 71", false, 0, 0));
        levelScores.Add(new LevelScores("Level 72", false, 0, 0));
        levelScores.Add(new LevelScores("Level 73", false, 0, 0));
        levelScores.Add(new LevelScores("Level 74", false, 0, 0));
        levelScores.Add(new LevelScores("Level 75", false, 0, 0));
        levelScores.Add(new LevelScores("Level 76", false, 0, 0));
        levelScores.Add(new LevelScores("Level 77", false, 0, 0));
        levelScores.Add(new LevelScores("Level 78", false, 0, 0));
        levelScores.Add(new LevelScores("Level 79", false, 0, 0));
        levelScores.Add(new LevelScores("Level 80", false, 0, 0));
        levelScores.Add(new LevelScores("Level 81", false, 0, 0));
        levelScores.Add(new LevelScores("Level 82", false, 0, 0));
        levelScores.Add(new LevelScores("Level 83", false, 0, 0));
        levelScores.Add(new LevelScores("Level 84", false, 0, 0));
        levelScores.Add(new LevelScores("Level 85", false, 0, 0));
        levelScores.Add(new LevelScores("Level 86", false, 0, 0));
        levelScores.Add(new LevelScores("Level 87", false, 0, 0));
        levelScores.Add(new LevelScores("Level 88", false, 0, 0));
        levelScores.Add(new LevelScores("Level 89", false, 0, 0));
        levelScores.Add(new LevelScores("Level 90", false, 0, 0));
        levelScores.Add(new LevelScores("Level 91", false, 0, 0));
        levelScores.Add(new LevelScores("Level 92", false, 0, 0));
        levelScores.Add(new LevelScores("Level 93", false, 0, 0));
        levelScores.Add(new LevelScores("Level 94", false, 0, 0));
        levelScores.Add(new LevelScores("Level 95", false, 0, 0));
        levelScores.Add(new LevelScores("Level 96", false, 0, 0));
        levelScores.Add(new LevelScores("Level 97", false, 0, 0));
        levelScores.Add(new LevelScores("Level 98", false, 0, 0));
        levelScores.Add(new LevelScores("Level 99", false, 0, 0));
        levelScores.Add(new LevelScores("Level 100", false, 0, 0));
    }
}
